##
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php: [5.5, hhvm]

matrix:
    allow_failures:
        - php: hhvm

env:
    - GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache

before_script:
    - composer require --dev --no-update phpunit/phpunit:"~4.1"
    - curl -sS http://bldr.io/installer | php

script:
    - ./bldr.phar build travis

notifications:
    irc: "irc.freenode.org#gushphp"
