#
# This file is part of Gush.
#
# (c) Luis Cordova <cordoval@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#

language: php

php: [5.5, hhvm-nightly]

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm-nightly

env:
    - GUSH_HOME=/tmp/gush GUSH_CACHE_DIR=/tmp/gush/cache

before_install:
    - curl -sS http://bldr.io/installer | php
    - php ./bldr.phar install

script:
    - php ./bldr.phar run travis
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php ./bldr.phar run -t secure travis; fi;'

notifications:
    irc: "irc.freenode.org#gushphp"
